spring:
  application:
    name: index-config-server
  cloud:
    config: #读取哪个仓库哪个分支的哪个目录
      label: master #分支
      server:
        git:
          search-paths: config #表明目录
          uri: https://github.com/cleariove/trend-trading #github仓库地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka