spring:
  application:
    name: trend-trading-backtest-view
  #增加thymeleaf配置
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
#表示注册到eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka